# Generated by Django 5.0.6 on 2024-05-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoFitofarmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(max_length=100)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientofitofarmaceutico_set', to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_suelo', models.CharField(max_length=100)),
                ('registro_fecha', models.DateField()),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_set', to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('fecha_analisis', models.DateField()),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisiscalidad_set', to='core.variedad')),
            ],
        ),
    ]
