# Generated by Django 5.0.7 on 2024-07-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_semilla', models.FloatField()),
                ('costo_sustrato', models.FloatField()),
                ('costo_energia', models.FloatField()),
                ('costo_agua', models.FloatField()),
                ('costo_manobra', models.FloatField()),
                ('presupuesto', models.FloatField()),
                ('produccion_gramos', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CannabisPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('effects', models.TextField()),
                ('flavor', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_en_inventario', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_socio', models.CharField(max_length=10, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('detalles', models.TextField()),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('metodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Suministros', 'Suministros'), ('Personal', 'Personal'), ('Otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('lista_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listamateriales')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='materiales',
            field=models.ManyToManyField(through='core.ItemListaMateriales', to='core.material'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10)),
                ('pagado', models.BooleanField(default=False)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('tipo_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.muestra')),
                ('tipo_analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField()),
                ('resultados', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('analisis_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analisisprogramado')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asignado_a', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoFitofarmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=200)),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(max_length=100)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_fitofarmaceuticos', to='core.variedad')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.variedad'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.miembro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_plantas', models.IntegerField()),
                ('area_cultivo', models.FloatField(help_text='Área de cultivo en m²')),
                ('luz_intensidad', models.FloatField(help_text='Intensidad de luz en lúmenes')),
                ('luz_horas', models.FloatField(help_text='Horas de luz por día')),
                ('temperatura_dia', models.FloatField(help_text='Temperatura durante el día en °C')),
                ('humedad', models.FloatField(help_text='Humedad relativa en %')),
                ('ph', models.FloatField(help_text='Nivel de pH del suelo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_fecha', models.DateField()),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('tipo_suelo', models.CharField(choices=[('arcilloso', 'Arcilloso: Alta proporción de arcilla, retiene agua y nutrientes.'), ('arenoso', 'Arenoso: Mucha arena, muy permeable, retiene menos agua y nutrientes.'), ('limoso', 'Limoso: Textura suave, retiene agua y nutrientes.'), ('humifero', 'Humífero: Rico en materia orgánica y nutrientes, muy fértil.'), ('calcareo', 'Calcáreo: Alto contenido de calcio, afecta el pH del suelo.'), ('salino', 'Salino: Concentraciones altas de sales solubles, perjudicial para cultivos.'), ('turba', 'Turba: Suelo orgánico de descomposición vegetal.')], max_length=100)),
                ('ph_suelo', models.FloatField(default=7.0)),
                ('nutrientes', models.CharField(default='normal', max_length=100)),
                ('iluminacion', models.FloatField(default=0.0)),
                ('temperatura_suelo', models.FloatField(default=0.0)),
                ('humedad_suelo', models.FloatField(default=0.0)),
                ('temperatura_ambiente', models.FloatField(default=0.0)),
                ('humedad_ambiente', models.FloatField(default=0.0)),
                ('concentracion_co2', models.FloatField(default=400.0)),
                ('ventilacion', models.CharField(default='normal', max_length=100)),
                ('oxigeno_suelo', models.FloatField(default=0.0)),
                ('calidad_agua_ph', models.FloatField(default=6.0)),
                ('calidad_agua_cloro', models.FloatField(default=0.0)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('fecha_analisis', models.DateField()),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='core.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variedad')),
            ],
        ),
    ]
