# Generated by Django 5.0.6 on 2024-05-24 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisiscalidad',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='core.variedad'),
        ),
        migrations.AlterField(
            model_name='condicionescultivo',
            name='humedad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='condicionescultivo',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='condicionescultivo',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='core.variedad'),
        ),
        migrations.AlterField(
            model_name='tratamientofitofarmaceutico',
            name='tratamiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamientofitofarmaceutico',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='core.variedad'),
        ),
    ]
