# Generated by Django 5.0.6 on 2024-05-25 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analisiscalidad_variedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientofitofarmaceutico',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_fitofarmaceuticos', to='core.variedad'),
        ),
    ]
