# Generated by Django 5.0.6 on 2024-07-08 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240707_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.variedad'),
        ),
    ]
