# Generated by Django 5.0.6 on 2024-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_variedad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionescultivo',
            name='nutrientes',
            field=models.CharField(default='normal', max_length=100),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='ph_suelo',
            field=models.FloatField(default=7.0),
        ),
    ]
