# Generated by Django 5.0.6 on 2024-07-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gastooperativo_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastooperativo',
            name='variedad',
        ),
    ]
