# Generated by Django 5.0.6 on 2024-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_condicionescultivo_nutrientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionescultivo',
            name='calidad_agua_cloro',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='calidad_agua_ph',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='concentracion_co2',
            field=models.FloatField(default=400.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='humedad_ambiente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='humedad_suelo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='iluminacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='oxigeno_suelo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='temperatura_ambiente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='temperatura_suelo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='condicionescultivo',
            name='ventilacion',
            field=models.CharField(default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='condicionescultivo',
            name='tipo_suelo',
            field=models.CharField(choices=[('arcilloso', 'Arcilloso: Alta proporción de arcilla, retiene agua y nutrientes.'), ('arenoso', 'Arenoso: Mucha arena, muy permeable, retiene menos agua y nutrientes.'), ('limoso', 'Limoso: Textura suave, retiene agua y nutrientes.'), ('humifero', 'Humífero: Rico en materia orgánica y nutrientes, muy fértil.'), ('calcareo', 'Calcáreo: Alto contenido de calcio, afecta el pH del suelo.'), ('salino', 'Salino: Concentraciones altas de sales solubles, perjudicial para cultivos.'), ('turba', 'Turba: Suelo orgánico de descomposición vegetal.')], max_length=100),
        ),
    ]
