# Generated by Django 5.0.6 on 2024-06-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_condicionescultivo_calidad_agua_cloro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_plantas', models.IntegerField()),
                ('area_cultivo', models.FloatField(help_text='Área de cultivo en m²')),
                ('luz_intensidad', models.FloatField(help_text='Intensidad de luz en lúmenes')),
                ('luz_horas', models.FloatField(help_text='Horas de luz por día')),
                ('temperatura_dia', models.FloatField(help_text='Temperatura durante el día en °C')),
                ('humedad', models.FloatField(help_text='Humedad relativa en %')),
                ('ph', models.FloatField(help_text='Nivel de pH del suelo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variedad')),
            ],
        ),
    ]
