# Generated by Django 5.0.6 on 2024-07-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gastooperativo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variedad'),
        ),
    ]
