# Generated by Django 5.0.6 on 2024-06-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_semilla', models.FloatField()),
                ('costo_sustrato', models.FloatField()),
                ('costo_energia', models.FloatField()),
                ('costo_agua', models.FloatField()),
                ('costo_manobra', models.FloatField()),
                ('presupuesto', models.FloatField()),
                ('produccion_gramos', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
