# Generated by Django 5.0.6 on 2024-06-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_muestra_tipo_delete_tipomuestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='tipo',
        ),
        migrations.AddField(
            model_name='muestra',
            name='tipo_analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoanalisis'),
        ),
    ]
