# Generated by Django 5.0.6 on 2024-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_muestra_tipo_muestra_tipo_analisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='resultados',
            field=models.TextField(),
        ),
    ]
