# Generated by Django 5.0.6 on 2024-06-24 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_plantacion_pedido_gastooperativo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='plantacion',
        ),
        migrations.RemoveField(
            model_name='gastooperativo',
            name='plantacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='plantacion',
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='variedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.variedad'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='variedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.variedad'),
        ),
        migrations.AddField(
            model_name='venta',
            name='variedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.variedad'),
        ),
        migrations.DeleteModel(
            name='Plantacion',
        ),
    ]
