# Generated by Django 5.0.6 on 2024-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_miembro_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='miembro',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='periodo',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_socio',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
