# Generated by Django 5.0.6 on 2024-06-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_miembro_usuario_miembro_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_socio',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
