# Generated by Django 5.0.6 on 2024-07-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_miembro_apellido_alter_miembro_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannabisPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('effects', models.TextField()),
                ('flavor', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
